basePath: /api/v1
definitions:
  myservice.myServiceError:
    properties:
      code:
        type: integer
      description:
        type: string
      error:
        type: string
    type: object
  myservice.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  myservice.signUpInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  myservice.signUpOutput:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
info:
  contact:
    email: razmolodinivan@mail.ru
  title: POS-Ninja Backend API
  version: 0.1-alpha
paths:
  /auth/signIn:
    post:
      consumes:
      - application/json
      parameters:
      - description: '`org`(default) or `employee`'
        in: query
        name: type
        type: string
      - description: Объект с обязательными полями `email` и `password`
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/myservice.signInInput'
      produces:
      - text/plain
      responses:
        "200":
          description: Возвращает `jwt токен` при успешной авторизации
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Вход для организации, либо сотрудника
  /auth/signUp:
    post:
      consumes:
      - application/json
      parameters:
      - description: '`org`(default) or `employee`'
        in: query
        name: type
        type: string
      - description: Объект с обязательными полями `email` и `password`
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/myservice.signUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/myservice.signUpOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/myservice.myServiceError'
      summary: Регистрация организации, либо сотрудника
swagger: "2.0"
