basePath: /api/v1
definitions:
  myservice.myServiceError:
    properties:
      code:
        type: integer
      description:
        type: string
      error:
        type: string
    type: object
  myservice.signInOrgInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  myservice.signInOrgOutput:
    properties:
      token:
        type: string
    type: object
  myservice.signUpOrgInput:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
  myservice.signUpOrgOutput:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
info:
  contact:
    email: razmolodinivan@mail.ru
  title: POS-Ninja Backend API
  version: 0.1-alpha
paths:
  /auth/signIn:
    post:
      consumes:
      - application/json
      description: |-
        Метод позволяет войти в аккаунт организации, либо сотрудника.
        Для входа сотрудника требуется `jwt токен` соотвествующей ему огранизации.
      parameters:
      - description: '`org`(default) or `employee`'
        in: query
        name: type
        type: string
      - description: Объект для входа в огранизацию. Обязательные поля:`email`, `password`
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/myservice.signInOrgInput'
      produces:
      - application/json
      responses:
        "200":
          description: Возвращает `jwt токен` при успешной авторизации
          schema:
            $ref: '#/definitions/myservice.signInOrgOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/myservice.myServiceError'
      summary: Вход для организации, либо сотрудника
  /auth/signUp:
    post:
      consumes:
      - application/json
      description: |-
        Метод позволяет зарегистрировать организацию или сотрудника данной огранизации.
        Регистрация сотрудника возможна только с `jwt токеном` организации.
      parameters:
      - description: '`org`(default) or `employee`'
        in: query
        name: type
        type: string
      - description: Объект для регитсрации огранизации. Обязательные поля:`email`,
          `password`
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/myservice.signUpOrgInput'
      produces:
      - application/json
      responses:
        "201":
          description: Возвращаемый объект при регистрации огранизации
          schema:
            $ref: '#/definitions/myservice.signUpOrgOutput'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/myservice.myServiceError'
      summary: Регистрация организации, либо сотрудника
swagger: "2.0"
